services:
  - type: web
    name: alx-travel-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn alx_travel_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alx_travel_app.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: RABBITMQ_URL
        sync: false  # youâ€™ll set this later

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A alx_travel_app worker -l info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alx_travel_app.settings
      - key: RABBITMQ_URL
        sync: false
